# Generated by Django 4.0.3 on 2022-03-24 03:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='./images/')),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='./images/')),
            ],
            options={
                'db_table': 'Images',
            },
        ),
        migrations.CreateModel(
            name='ItemClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('genre_id', models.IntegerField()),
            ],
            options={
                'db_table': 'ItemClasification',
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('image_id', models.IntegerField()),
            ],
            options={
                'db_table': 'ItemImage',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=40)),
                ('item_description', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 3, 24, 3, 34, 18, 686612, tzinfo=utc))),
                ('item_eval', models.IntegerField(default=0)),
                ('is_deal', models.BooleanField(default=False)),
                ('icon', models.ImageField(default='./images/default_user.png', upload_to='./static/apps/')),
            ],
            options={
                'db_table': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('item_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Likes',
            },
        ),
        migrations.CreateModel(
            name='Universities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('university_name', models.CharField(max_length=30)),
                ('university_domain', models.URLField()),
            ],
            options={
                'db_table': 'Universities',
            },
        ),
        migrations.CreateModel(
            name='UserListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('item_id', models.IntegerField()),
            ],
            options={
                'db_table': 'UserListing',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_pass', models.CharField(max_length=30)),
                ('university', models.IntegerField()),
                ('icon', models.ImageField(default='./images/default_user.png', upload_to='./images')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
