# Generated by Django 3.2.9 on 2022-03-05 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='genres',
            table='Genres',
        ),
        migrations.AlterModelTable(
            name='images',
            table='Images',
        ),
        migrations.AlterModelTable(
            name='itemclassification',
            table='ItemClasification',
        ),
        migrations.AlterModelTable(
            name='itemimage',
            table='ItemImage',
        ),
        migrations.AlterModelTable(
            name='items',
            table='Items',
        ),
        migrations.AlterModelTable(
            name='likes',
            table='Likes',
        ),
        migrations.AlterModelTable(
            name='universities',
            table='Universities',
        ),
        migrations.AlterModelTable(
            name='userlisting',
            table='UserListing',
        ),
        migrations.AlterModelTable(
            name='users',
            table='Users',
        ),
    ]
