# Generated by Django 3.2.9 on 2022-03-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_alter_users_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='icon',
            field=models.ImageField(upload_to='./images'),
        ),
    ]
