# Generated by Django 3.2.9 on 2022-03-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_auto_20220316_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='icon',
            field=models.ImageField(default='./images/default_user.png', upload_to='./images'),
        ),
    ]
