# Generated by Django 3.2.9 on 2022-03-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_items_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='icon',
            field=models.ImageField(default='./images/default_user.png', upload_to='./images'),
        ),
    ]
