# Generated by Django 3.2.9 on 2022-03-23 06:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_alter_items_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 23, 6, 15, 49, 38078, tzinfo=utc)),
        ),
    ]
