# Generated by Django 3.2.9 on 2022-03-24 03:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_auto_20220323_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='first',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='check',
            name='last',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='items',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 24, 3, 14, 27, 447931, tzinfo=utc)),
        ),
    ]
