# Generated by Django 3.2.9 on 2022-03-24 03:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_auto_20220324_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 24, 3, 18, 39, 563760, tzinfo=utc)),
        ),
        migrations.AlterModelTable(
            name='check',
            table='Check',
        ),
    ]
