# Generated by Django 3.2.9 on 2022-03-25 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_auto_20220324_0334'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Check',
        ),
        migrations.DeleteModel(
            name='ItemClassification',
        ),
        migrations.DeleteModel(
            name='ItemImage',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
        migrations.DeleteModel(
            name='UserListing',
        ),
        migrations.RemoveField(
            model_name='users',
            name='university',
        ),
    ]
