# Generated by Django 3.2.9 on 2022-03-25 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_auto_20220325_1309'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Universities',
        ),
    ]
