# Generated by Django 3.2.9 on 2022-03-25 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0020_delete_universities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
